version: "3"
services:
  api:
    container_name: go_container
    build:
      context: ./src
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./src:/go/src

  db:
    container_name: bcm_db_container
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - bcm-dev-db-volume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  bcm-dev-db-volume:
